### ISSUE TITLE
Error activating extension: Cannot find module '@jarna/toml'

### ISSUE THREAD

**Issue by adamc55** [Shellomo/vscode_ext_enhanced_toml#1]
The message is:
`
`mainThreadExtensionService.ts:107 Activating extension 'Shellomo.enhanced-toml' failed: Cannot find module '@iarna/toml'
Require stack:
- c:\Users\adamc\.vscode\extensions\shellomo.enhanced-toml-1.0.3\out\extension.js
- c:\Users\adamc\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js.`

**Comment by Shellomo** [comment]
@adamc55 Thank you for reporting this issue. I've fixed the dependency problem by updating the extension packaging configuration to properly include the required @iarna/toml module. The fix has been published in version 1.0.5, which is now available on the VS Code Marketplace.
Please update to the latest version, and let me know if you encounter any other issues.
